### PR TITLE
M1 Build attempt

### PR DESCRIPTION
**Pull request by XapaJIaMnu**
First attempt to get M1 build on the workflows

### CODE REVIEW

**Comment by muzzah** [comment]
Just wanted to confirm, does the ARM Mac releases still require rosetta at the moment? I prefer not to download rosetta and the Mac release is asking me to download it still

**Comment by XapaJIaMnu** [comment]
We still don't have an automated m1 build. Github offers m1 runners but I don't have access to m1 hardware myself to debug it and set it up.

For now native m1 build is only available if you build it yourself, sorry;/

**Comment by jelmervdl** [comment]
@XapaJIaMnu I have a personal M3 MacBook now, when I find some time I can give it a go.

**Comment by jelmervdl** [comment]
Build seems to be working, signing fails though. Definitely an expired key, but also the arm build has some parse errors of which I don't know the source.

**Pull request merged**
